language: python
python:
  - 3.5
sudo: false
env:
  global:
    - WHEELHOST="travis-wheels.scikit-image.org"
    - WHEELHOUSE="http://travis-wheels.scikit-image.org/"
    - DEPENDS="numpy scipy"
addons:
  apt:
    packages:
      - libportaudio2
install:
  - pip install -r requirements-dev.txt
  - pip install --no-index --trusted-host $WHEELHOST --find-links $WHEELHOUSE $DEPENDS
  - pip install .
script:
  - py.test
